---
title: "Pauta para el trabajo personal de análisis exploratorio de datos"
subtitle: 'Diplomado en Análisis de Datos y Modelamiento Predictivo con Aprendizaje Automático para la Acuicultura.'
author:
 name: Dr. José A. Gallardo Matus y Dra. María Angélica Rueda
 affiliation: Pontificia Universidad Católica de Valparaíso
 email: <jose.gallardo@pucv.cl>
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
  word_document: default
  pdf_document: default
---

<style>
#TOC {
  color: black;
  font-familiy: Calibri;
  font-size: 14px;
  border-color: #708090; 
}
body {
   color: black;
   font-familiy: Calibri;
}

pre {
  color: black;
  background-color: #F8F8FF;
}
# header {
  color: #800000;
  font-familiy: Calibri;
  background-color: #F5F5F5;
  opacity: 0.8;
  font-size: 16px;
}
</style>

```{r setup, include=FALSE, warning=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### DESCRIPCIÓN DEL PROYECTO PERSONAL DE ANÁLISIS DE DATOS.

El **trabajo** corresponde a un proyecto personal de análisis exploratorio de datos de Acuicultura con R. El trabajo se puede realizar simulando datos, mediante el uso de datos propios (ej. de su trabajo o empresa), o mediante la recopilación de datos desde cualquier base de datos pública.

### OBJETIVOS.

Los objetivos del proyecto personal de análisis de datos son:

**1)** Elaborar repositorio **GitHub** y mantener control de versiones del trabajo realizado, cada día de trabajo debe quedar registrado en el repositorio.

**2)** Elaborar análisis exploratorio de datos en formato html usando **Rmarkdown**.

### EVALUACIÓN DEL TRABAJO.

**Parámetros para el cálculo de la nota.**

|  **Item** | **valor**      |
|:-------------|:------------------|
| **Nota máxima** | 7,0 |
| **Nota mínima** | 1,0 |
| **Nota aprobación** | 4,0 |
| **Exigencia para aprobar** | 60% |
| **Puntaje máximo** | 32 |

**Puntaje según nivel de logro alcanzado en cada componente evaluado.**

|  **Nivel de logro** | **Puntaje**      |
|:-------------|:------------------|
| **Excelente** | 4 |
| **Muy bueno** | 3 |
| **Bueno** | 2 |
| **Suficiente** | 1 |
| **Insuficiente** | 0 |

**Fecha y modo de entrega**

El reporte del análisis exploratorio se realiza enviando el documento en formato HTML antes del sábado 20 de mayo a las 23:59 PM al siguiente correo electrónico: <acuicultura@pucv.cl>

### CONTENIDO MÍNIMO Y PUNTAJE.

**Proyecto Git Hub.**  \
&nbsp;  
1. Evidencias del uso de control de versiones en github **(4 puntos)**.    
2. Archivo README en github **(4 puntos)**: Incluye título del trabajo, autor y un párrafo con la descripción del problema a resolver.\
&nbsp;   
Incluye además un párrafo con la descripción de las variables de estudio, los factores que se desean analizar y el número total de observaciones.  \
&nbsp;   

**Proyecto Rstudio.cloud y reporte con análisis exploratorio de datos.**  \
&nbsp;  
3. Describe la variación de las variables de estudio usando histogramas **(4 puntos)**.  \
&nbsp;  
4. Identifica si los datos están balanceados o no entre tratamientos usando tablas de frecuencia **(4 puntos)**.  \
&nbsp;  
5. Establece relación entre variables cuantitativas y factores usando gráficas avanzadas de correlación, boxplot, interacción, de tamaño de los efectos entre otras **(4 puntos)**.  \
&nbsp;  
6. Identifica si existen errores, datos faltantes, datos duplicados o valores atípicos y resuelve estos problemas usando R **(4 puntos)**.  \
&nbsp;  
7. Resume los datos usando tablas y estadística descriptiva con R **(4 puntos)**.  \
&nbsp;  
8. Utiliza paquetes para importar datos a R como **readxl** o similar, y paquetes **tidyr** **dplyr**, **ggplot2** para el análisis exploratorio de datos o similar según la naturaleza de los datos **(4 puntos)**.  

 